name: Auto Deploy to Render
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -fsSL -X POST "https://api.render.com/deploy/srv-d2b5020gjchc73eue16g?key=M-cQXgZvXXQ"
